### ISSUE TITLE
Update documentation to indicate this works on Catalina

### ISSUE THREAD

**Issue by jasonfharris** [rkanter/Open-iTerm-or-Terminal-Here...#4]
It wasn't immediately obvious that this worked in Catalina, but it does... The documentation should likely be updated?

**Comment by rkanter** [comment]
I haven't upgraded to Catalina yet, so I haven't been able to test it; but I'm glad it's working on Catalina.  I'll update the docs about that soon.  Thanks for letting me know!

**Comment by rkanter** [comment]
Fixed by 8eb93189496486c19a331fd0c3712468d81c40bc

**Comment by jasonfharris** [comment]
Thanks! (I might have a small nit that it is nice to see each OS listed so the user knows the project isn't "state".) But that is a definite improvement. Thanks!
